// Shared research data, consumed by both the homepage §Research section and
// the full /research page. Edit authors / add figure images here.
//
// figure: path under /public, e.g. '/assets/images/research/<slug>.png'.
//   If the image is missing it falls back to a typeset placeholder showing
//   `figureLabel`, so it's safe to ship before the figures exist.

// `me` marks the author entry to emphasize in the rendered list (Ashmit is a
// co-author, not first author, on all of these).
export const me = 'A. Dutta';

export const publications = [
  {
    slug: 'llm-reasoning',
    title:
      'The Challenge of Teaching Reasoning to LLMs Without RL or Distillation',
    authors: ['W. Du', 'B. Kisacanin', 'G. Armstrong', '…', me, '…', 'B. Ginsburg', 'I. Gitman'],
    venue: 'ICML 2025 — AI for Math Workshop',
    year: 2025,
    href: 'https://arxiv.org/abs/2507.09850',
    figure: '/assets/images/reasoning.png',
    figureLabel: 'arXiv\n2507.09850',
    abstract:
      'Studies whether competitive chain-of-thought reasoning can be elicited in language models through supervised finetuning alone, without reinforcement learning or distillation from a stronger teacher.',
  },
  {
    slug: 'uchicago-gnn',
    title:
      'Multi-Modal Graph Neural Networks for Neutrino Event Reconstruction',
    authors: [me, 'A. Helal', 'G. Cerati', 'D. Grzenda', 'V. Hewes'],
    venue: 'UChicago Data Science Institute — DSI Summer Lab (Fermilab Exa.TrkX)',
    year: 2024,
    href: 'https://datascience.uchicago.edu/people/ashmit-dutta-he-him/',
    linkLabel: 'poster',
    figure: '/assets/images/gnn.png',
    figureLabel: 'DSI\n2024',
    abstract:
      "Poster on multi-modal graph neural networks built on HPC clusters for Fermilab's Exa.TrkX neutrino reconstruction project, fusing wire-plane spacepoints and optical PMT hits to reconstruct neutrino events.",
  },
  {
    slug: 'sunflower-3d',
    title:
      'A Novel AI-Based Technique for 3D Shape Acquisition of Confectionery Sunflower Seeds and Associated Shape Descriptors',
    authors: ['N. Hladni', 'B. Kisačanin', 'V. Petrović', me, 'V. Miklič', 'D. Miladinović'],
    venue: '21st International Sunflower Conference',
    year: 2024,
    href: 'https://fiver.ifvcns.rs/handle/123456789/4861?locale-attribute=en',
    linkLabel: 'proceedings',
    figure: '/assets/images/NeRF_Output.jpg',
    figureLabel: 'ISC\n2023',
    abstract:
      'A computer-vision pipeline for reconstructing the 3D geometry of confectionery sunflower seeds and deriving quantitative shape descriptors for downstream phenotyping.',
  },
  {
    slug: 'quantum-noise',
    title:
      'Simulation Costs for Quantum Dynamical Semigroups Generated by Lindbladians',
    authors: [],
    venue: 'Illinois Mathematics Lab',
    year: 2024,
    href: '/assets/docs/IML_SP24.pdf',
    poster: '/assets/images/IML.png',
    figure: '/assets/images/IML.png',
    figureLabel: 'IML\n2024',
    abstract:
      'Estimates upper and lower bounds on the cost of simulating quantum dynamical semigroups generated by Lindbladians on quantum hardware, using customized gate resource sets rather than universal gates.',
  },
  {
    slug: 'orbital-resonance',
    title: 'An Analytic Model of Stable and Unstable Orbital Resonance',
    authors: ['V. Jayam', 'K. Thaman', 'J. Kim', 'S. Jain', 'Q. Xue', me],
    venue: '52nd Lunar and Planetary Science Conference (LPSC)',
    year: 2021,
    href: '/assets/docs/resonance.pdf',
    published: 'https://ui.adsabs.harvard.edu/abs/2021LPI....52.2764J/abstract',
    figure: '/assets/images/resonance.png',
    figureLabel: 'LPSC\n2021',
    abstract:
      'Theoretical astrophysics work developing an analytic framework for stable and unstable mean-motion orbital resonances, accepted for presentation at LPSC 2021.',
  },
];

export const researchExperience = [
  {
    title: 'Assured & Trustworthy AI Lab',
    org: 'UIUC · Prof. Huan Zhang',
    href: 'https://www.huan-zhang.com/',
    period: '2025 – Present',
    description: (
      <>
        Research on formal neural-network verification, contributing to{' '}
        <a
          href="https://github.com/Verified-Intelligence/auto_LiRPA"
          target="_blank"
          rel="noreferrer"
        >
          auto_LiRPA
        </a>{' '}
        and{' '}
        <a
          href="https://github.com/Verified-Intelligence/alpha-beta-CROWN"
          target="_blank"
          rel="noreferrer"
        >
          α-β-CROWN
        </a>
        , state-of-the-art tools for certifying robustness bounds on deep
        networks.
      </>
    ),
  },
  {
    title: 'ML Research Intern',
    org: 'UChicago Data Science Institute',
    href: 'https://datascience.uchicago.edu/people/ashmit-dutta-he-him/',
    period: 'Jun 2024 – Aug 2024',
    description: (
      <>
        Built multi-modal graph neural networks on HPC clusters for Fermilab's{' '}
        <i>Exa.TrkX</i> neutrino reconstruction project.
      </>
    ),
  },
  {
    title: 'Undergraduate Researcher · WaggleNet',
    org: 'UIUC · Prof. Christopher Schmitz',
    href: 'https://www.wagglenet.org/',
    period: '2024',
    description: (
      <>
        Designed and deployed IoT systems for beekeepers; worked on the audio
        team combining hardware and ML models to capture hive audio and predict
        bee behavior.
      </>
    ),
  },
];
