name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (if needed)
        run: |
          # If you have a build step, put it here and output to a folder like 'dist'
          # For pure static sites, you can remove this step.
          echo "No build step"

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload static content
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'          # <- Change to your output dir (e.g., 'dist' or 'build')
          # name: github-pages  # optional (default is fine)
          # retention-days: 1   # optional

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
